version: 2

formats:
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python:
      version: 3.8
      install:
        - requirements: requirements.txt
        - method: pip
          path: .
          extra_requirements:
            - doc
        - method: setuptools
          path: .
      system_packages: true


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py