site_name: AGVis
site_url: https://agvis.readthedocs.io
nav:
  - Home: 'index.md'
  - 'Quick Start': 'quick_start/quick_start.md'
  - Examples: 'examples/examples.md'
  - 'Release Notes': 'release-notes.md'
theme: readthedocs
