site_name: AGVis
site_url: https://agvis.readthedocs.io
nav:
  - Home: 'index.md'
  - 'Quick Start': 'quick_start/quick_start.md'
  - Examples:
          - 'Configuration': 'examples/examples.md'
          - 'MultiLayer': 'examples/multi.md'
          - 'Independent Data Reader': 'examples/idr.md'
  - About:
          - 'Release Notes': 'release-notes.md'
theme: readthedocs
